- name: update_3d_printer
  hosts: all  # Targeting all hosts defined in your inventory
  become: yes # Required for running system updates and reboot
  vars:
    moonraker_port: 7125 # Default Moonraker API port

  tasks:

    - name: Get Moonraker printer status
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}:{{ moonraker_port }}/printer/objects/query?idle_timeout"
        method: GET
        return_content: true
        status_code: 200
      register: printer_status_check
      delegate_to: localhost # Run the API check from the Ansible controller

    - name: Set fact for printer state
      ansible.builtin.set_fact:
        printer_state: "{{ (printer_status_check.content | from_json)['result']['status']['idle_timeout']['state'] }}"

    - name: Report current status
      ansible.builtin.debug:
        msg: "Printer state on {{ inventory_hostname }} is: {{ printer_state }}"
        
    # --- Conditional Block for OS Updates ---
    - block:
        
        - name: Update package cache and upgrade all system packages
          ansible.builtin.apt:
            update_cache: yes
            upgrade: dist
            autoremove: yes

        - name: Check if a reboot is required after update
          ansible.builtin.stat:
            path: /var/run/reboot-required
          register: reboot_required

        - name: Reboot the printer host if required
          ansible.builtin.reboot:
            reboot_timeout: 600 # Wait up to 10 minutes for reboot
          when: reboot_required.stat.exists

      # THIS IS THE CRITICAL GUARDRAIL: Only run if the state is NOT 'Printing'
      when: printer_state != 'printing'

    - name: Notify if update was skipped due to print
      ansible.builtin.debug:
        msg: "Update on {{ inventory_hostname }} was SKIPPED because the state is '{{ printer_state }}'. The print is safe."
        # This task will only run if the 'block' above was skipped due to the 'when' condition
      when: printer_state == 'printing'
