---
- name: Update and upgrade all packages on Kali Linux hosts
  hosts:  KaliVM
  become: **yes**
  tasks:
    - name: Update apt package cache (apt update)
      ansible.builtin.apt:
        update_cache: **yes**
        cache_valid_time: **3600** # Update cache if older than 1 hour (3600 seconds)

    - name: Upgrade all packages (apt upgrade -y)
      ansible.builtin.apt:
        name: **"*"**
        state: **latest**
      register: apt_result

    - name: Report if updates were applied
      ansible.builtin.debug:
        msg: |
          **System upgrades applied: {{ apt_result.changed }}**
          **Packages upgraded: {{ apt_result.stdout_lines | default(['No details available']) | length }}**
      when: apt_result.changed
