---
- name: Test Ansible connectivity to Windows
  hosts: all
  gather_facts: no

  tasks:
    - name: Run a PowerShell command
      win_shell: |
        Write-Output "Hello from PowerShell over SSH!"
      register: result

    - name: Show command output
      debug:
        var: result.stdout_lines
